#!/bin/sh

echo "Grab a version of macports and the compilers here:";
echo "https://distfiles.macports.org/MacPorts/";
echo;
echo "https://github.com/kennethreitz/osx-gcc-installer";

hash git &> /dev/null
if [ $? -eq 1 ]; then
		echo "You need to install git.";
		printf 'Install? [y/n]: 'read -r INPUT;
		case $INPUT in
				y)
						sudo port install git-core > /dev/null;
						;;
				n)
						;;
		esac
else
if [ `uname` = "Darwin" ]; then
	if [ -f 2bwm.c ]; then
		echo "We are in the git repo, continuing...";
	else
			printf 'Do you want to clone 2bwm git repo? [y/n]; '; read -r INPUT;
			case $INPUT in
					y)
						echo "Cloning the repo...";
						git clone https://github.com/venam/2bwm --quiet > /dev/null
						cp 2bwmonosx 2bwm;
						cd 2bwm;
						;;
					n)
						cp 2bwmonosx 2bwm;
						cd 2bwm
						;;
			esac
	fi
	echo;
	echo "Checking for dependencies..."
	echo
	if [ -f /opt/local/include/xcb/xcb.h ] && 
	   [ -f /opt/local/include/xcb/randr.h ] && 
	   [ -f /opt/local/include/xcb/xcb_keysyms.h ] && 
	   [ -f /opt/local/include/xcb/xcb_icccm.h ] && 
	   [ -f /opt/local/include/xcb/xcb_util.h ]; then 
	   echo "You seem to have the needed xcb libraries, let's build this:";
	   echo;
		 echo "Patching the Makefile for osx...";
	   awk '{gsub(/usr/, "opt"); print}' Makefile > Makefile.osx;
	   mv Makefile.osx Makefile;
	   echo;
	   echo "Modifying 2bwm path to /opt/local in config.h..."
		 echo;
	   echo "Changing the mod key to cmd(apple) key..."
	   awk '{gsub(/usr/, "opt"); sub(/XCB_MOD_MASK_4/, "XCB_MOD_MASK_2"); print}' config.h > config.h.osx;
	   mv config.h.osx config.h;
	   echo;
	   echo "Building..." 
	   make > /dev/null;
	   echo;
	   echo "and don't forget to check config.h";
	   echo;
	   printf 'Do you want to install now? [y/n]: '; read -r INPUT;
	   echo;
	   case $INPUT in
	   		y)
	   			sudo make install clean > /dev/null;
	   			echo "2bwm is now installed."
				;;
			n)
				echo "run 'sudo make install' to install"
				;;
		esac
	else
		echo "It seems that  xorg-libxcb, , xorg-xcb-util, xorg-xcb-util-wm";
		echo "and xorg-xcb-util-keysyms are not installed.";
		printf 'Do you want to install them now? [y/n]: '; read -r INPUT;
		case $INPUT in 
			y)
				sudo port install xorg-libxcb xorg-xcb-util xorg-xcb-util-wm xorg-xcb-util-keysyms > /dev/null;
				if [ -d 2bwm ]; then
					cd 2bwm;
					./2bwm/2bwmonosx
				else
					./2bwmonosx
				fi
				;;
			n)
				echo "Okay then, good luck!";
				;;
		esac
				
	fi
else
		make > /dev/null;
fi
fi
