#!/bin/bash

IC="\u5\b0\f1"
NO="\u2\b2"

Workspaces() {
		ACT=$(awk -f ~/Scripts/activewin.awk)
		#CUR=$(awk -f ~/Scripts/lastfm.awk)
		MPC=$(mpc -p 8000|head -1)
  	#UH=$(awk -f ~/Scripts/uh.awk)
		#MAIL=$(awk -f ~/Scripts/mail.awk)
		DATE=$(date "+%d/%H:%M")
		VOL=$(awk -f ~/Scripts/volume.awk)
		#NET=$(awk -f ~/Scripts/net.awk)
		cw_1=$(echo -n "")
		cw_2=$(echo -n "")
		cw_3=$(echo -n "")
		cw_4=$(echo -n "")
		cw_5=$(echo -n "")
		dksp_tag=('' $cw_1 $cw_2 $cw_3 $cw_4 $cw_5)
		CW=$(awk -f ~/Scripts/ws.awk) 
		tws=$(awk -f ~/Scripts/tws.awk) 
		for w in $(seq 1 $tws); do
				if [ "$w" -eq "$CW" ]; then
						buffer="$buffer\u5\b0\f1 ${dksp_tag[$w]} \u2\b2\f1"
				else
						buffer="$buffer\u2\b2 ${dksp_tag[$w]} \u2\b2" 
				fi
		done
		echo -n "\l${buffer} $IC  $NO\f5 $DATE \u5\b0\f1 $NO\f3 $VOL $IC $NO\b0\u5\f1  $NO $MPC \u5\b0\f1 \u2\b2 $ACT"
}

Info_Bar() {
		FANSPED=$(awk -f ~/Scripts/fan.awk)
		DISKUSD=$(df -h|awk '/disk0s2/ {print $8}')
		MEMUSED=$(awk -f ~/Scripts/mem.awk)
		BATTUSD=$(awk -f ~/Scripts/batt.awk)
		CPUTEMP=$(awk -f ~/Scripts/temp.awk)
		#CPUAVEG=$(cpu)
		echo -n "\r\b0\u5\f1  $NO\f6 $FANSPED \u5\b0\f1  \b2\u2\f5 $CPUTEMP \u5\b0\f1 \u2\b2\f6 $BATTUSD \u5\b0\f1  \u2\f5\b2 $DISKUSD \u5\b0\f1  \u2\b2\f3 $MEMUSED " 
}

while true; do
		echo "$(Workspaces)$(Info_Bar)"
		sleep 1;
done
