#!/bin/bash

IC="\u5\b0\f1"
NO="\u2\b2"
Left_Bar() {
		CW=$(awk -f ~/Scripts/ws.awk) 
  	UH=$(awk -f ~/Scripts/uh.awk)
		MAIL=$(awk -f ~/Scripts/mail.awk)
		DATE=$(date "+%d/%H:%M")
		VOL=$(awk -f ~/Scripts/volume.awk)
		NET=$(awk -f ~/Scripts/net.awk)
		echo -n "\l\u5\b0\f1 $NO\f3 $CW $IC  $NO\f5 $MAIL $IC  $NO\f6 $UH  $IC  $NO\f5 $DATE \u5\b0\f1 $NO\f3 $VOL $IC  $NO \f6$NET $IC  $NO" 
}

Right_Bar() {
		DISKUSD=$(df -h|awk '/disk0s2/ {print $8}')
		MEMUSED=$(awk -f ~/Scripts/mem.awk)
		BATTUSD=$(awk -f ~/Scripts/batt.awk)
		CPUTEMP=$(awk -f ~/Scripts/temp.awk)
		CPUAVEG=$(top -l 1|awk '/CPU usage/ {print $3}')
		echo -n "\r\b0\u5\f1  \b2\u2\f3 $CPUAVEG \u5\b0\f1  \b2\u2\f5 $CPUTEMP \u5\b0\f1 \u2\b2\f6 $BATTUSD \u5\b0\f1  \u2\f5\b2 $DISKUSD \u5\b0\f1  \u2\b2\f3 $MEMUSED " 
}

Center_Bar() {
		CUR=$(awk -f ~/Scripts/lastfm.awk)
		echo -n "\c\b0\u5\f1  \b2  $CUR \b0  \u2\b2"
}

while true; do
		echo "$(Right_Bar)$(Center_Bar)$(Left_Bar)"
		sleep 1;
done
